# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUQ9x6QRNH__e9f-mRPrSOqGRgvc5SRU
"""

import streamlit as st
import torch
import torch.nn.functional as F
import numpy as np
import cv2
import timm
import os
import gdown
from PIL import Image
from torchvision import transforms

st.set_page_config(page_title="DR Detection", page_icon="👁️", layout="wide")

# ---------- Custom CSS ----------
st.markdown("""
<style>
    .main-title {
        font-size: 2.6rem;
        font-weight: 800;
        background: linear-gradient(90deg, #2563eb, #06b6d4);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0;
    }
    .subtitle {
        color: #64748b;
        font-size: 1.05rem;
        margin-top: 0;
        margin-bottom: 1.5rem;
    }
    .result-card {
        background: #f8fafc;
        border-radius: 16px;
        padding: 1.5rem;
        border: 1px solid #e2e8f0;
        margin-top: 1rem;
    }
    .confidence-badge {
        display: inline-block;
        padding: 0.4rem 1rem;
        border-radius: 999px;
        font-weight: 700;
        font-size: 1.1rem;
        color: white;
    }
    .info-box {
        background: #eff6ff;
        border-left: 4px solid #2563eb;
        border-radius: 8px;
        padding: 1rem 1.2rem;
        margin-top: 1.5rem;
        font-size: 0.92rem;
        color: #1e3a5f;
    }
    .stButton>button {
        border-radius: 10px;
        font-weight: 600;
    }
</style>
""", unsafe_allow_html=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
IMG_SIZE = 256
class_names = ['No DR', 'Mild', 'Moderate', 'Severe', 'Proliferative DR']
class_colors = {
    'No DR': '#16a34a',
    'Mild': '#84cc16',
    'Moderate': '#f59e0b',
    'Severe': '#f97316',
    'Proliferative DR': '#dc2626'
}
CONFIDENCE_THRESHOLD = 45

MODEL_PATH = 'phase2_best.pt'
DRIVE_FILE_ID = '1dw4dIKaRJkrNzG9EaFuSd_ihF7rv1rrE'

@st.cache_resource
def load_model():
    if not os.path.exists(MODEL_PATH):
        with st.spinner("Downloading model weights (first launch only)..."):
            url = f'https://drive.google.com/uc?id={DRIVE_FILE_ID}'
            gdown.download(url, MODEL_PATH, quiet=False)

    model = timm.create_model('swinv2_tiny_window8_256', pretrained=False, num_classes=5, drop_rate=0.3)
    state_dict = torch.load(MODEL_PATH, map_location=device, weights_only=False)
    model.load_state_dict(state_dict)
    model.to(device)
    model.eval()
    return model

model = load_model()

gradients, activations = None, None

def save_gradient(grad):
    global gradients
    gradients = grad

def forward_hook(module, input, output):
    global activations
    activations = output
    output.register_hook(save_gradient)

target_layer = model.layers[-1].blocks[-1].norm2
target_layer.register_forward_hook(forward_hook)

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
])

def predict(image):
    img = image.convert('RGB')
    x = eval_transform(img).unsqueeze(0).to(device)
    x.requires_grad_()

    out = model(x)
    probs = F.softmax(out, dim=1).cpu().detach().numpy()[0]
    pred_class = int(probs.argmax())
    confidence = float(probs[pred_class] * 100)

    model.zero_grad()
    out[0, pred_class].backward()
    grads = gradients[0].detach().cpu()
    acts = activations[0].detach().cpu()
    weights = grads.mean(dim=0)
    cam = (weights * acts).sum(dim=-1)
    side = int(cam.shape[0] ** 0.5)
    cam = cam.reshape(side, side).numpy()
    cam = np.maximum(cam, 0)
    cam = cam / (cam.max() + 1e-8)
    cam = cv2.resize(cam, (IMG_SIZE, IMG_SIZE))

    img_resized = np.array(img.resize((IMG_SIZE, IMG_SIZE))) / 255.0
    heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET) / 255.0
    heatmap = heatmap[..., ::-1]
    overlay = (0.5 * img_resized + 0.5 * heatmap)
    overlay_img = (overlay * 255).astype(np.uint8)

    return pred_class, confidence, probs, overlay_img

# ---------- Header ----------
st.markdown('<p class="main-title">👁️ Diabetic Retinopathy Detection</p>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Upload a retinal fundus image for automated severity grading using Swin V2 Tiny</p>', unsafe_allow_html=True)

uploaded_file = st.file_uploader("📤 Choose a fundus image", type=['jpg', 'jpeg', 'png'])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    with st.spinner("Analyzing image..."):
        pred_class, confidence, probs, overlay_img = predict(image)

    pred_name = class_names[pred_class]
    color = class_colors[pred_name]

    col1, col2 = st.columns(2)
    with col1:
        st.image(image, caption="📷 Uploaded Image", use_container_width=True)
    with col2:
        st.image(overlay_img, caption=" Grad-CAM — Model Focus Area", use_container_width=True)

    st.markdown(f"""
    <div class="result-card">
        <span style="font-size:1.3rem; font-weight:700;">Prediction: {pred_name}</span><br><br>
        <span class="confidence-badge" style="background-color:{color};">
            {confidence:.1f}% confidence
        </span>
    </div>
    """, unsafe_allow_html=True)

    if confidence < CONFIDENCE_THRESHOLD:
        st.warning(f" Low confidence ({confidence:.1f}%) — this image may not be a valid "
                   f"retinal fundus photo, or quality may be too low for reliable grading.")

    st.markdown("####  Probability by Class")
    prob_data = {class_names[i]: float(probs[i]) for i in range(5)}
    st.bar_chart(prob_data)

st.markdown("""
<div class="info-box">
<b>ℹ️ About this model</b><br>
- Architecture: Swin Transformer V2 (Tiny)<br>
- Training: Leak-free, class-balanced split of a diabetic retinopathy fundus image dataset<br>
- Test set performance: QWK = 0.7972, macro-F1 = 0.6369, accuracy = 0.72<br>
- Prediction confidence reflects the model's certainty for this specific image, not a
  guarantee of correctness.
</div>
""", unsafe_allow_html=True)
